sudo: false
language: python
python:
  - "3.6"
install: pip install -r requirements.txt
before_script:
  - pip install pycodestyle
  - pip install nose2
  - pip install coverage
  - pip install commonconf
  - pip install coveralls
  - pip install pycodestyle

  - cp travis-ci/manage.py manage.py
  - manage.py migrate
script:
  - pycodestyle accountsynchr/ --exclude=resources
  - python -m compileall accountsynchr
  - coverage run --source=accountsynchr manage.py test accountsynchr
after_script:
  - coveralls
