sudo: false
language: python
python:
  - "3.6"

before_script:
  - pip install -e .
  - pip install pycodestyle
  - pip install coverage
  - pip install commonconf
  - pip install coveralls
  - cp travis-ci/manage.py manage.py
  - python manage.py migrate

script:
  - pycodestyle accountsynchr/ --exclude=resources
  - python -m compileall accountsynchr
  - coverage run --source=accountsynchr --omit=accountsynchr/resources/* manage.py test accountsynchr

after_script:
  - coveralls
