ingress:
  enabled: true
  tls:
    eventcal:
      secretName: eventcal.uw.edu-ingress-cert
      hosts:
        - eventcal.uw.edu
  hosts:
    eventcal:
      host: eventcal.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
  podsSpanNodes: true
readiness:
  enabled: true
externalService:
  enabled: true
  name: eventcal-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.24
  servicePort: 3306
database:
  engine: mysql
  name: eventcal_prod
  hostname: eventcal-db-service
  secretName: eventcal.uw.edu-sql-secrets
repo: eventcal
instance: prod
image:
  repository: registry.hub.docker.com/acait/eventcal
  tag: IMAGE_TAG
certs:
  mounted: true
  certPath: /certs/eventcal.uw.edu-uwca.cert
  keyPath: /certs/eventcal.uw.edu-uwca.key
  secretName: eventcal.uw.edu-uwca-certs

cronjob:
  enabled: true
  jobs:
    - name: sync-accounts-from-gws-to-trumba-day
      schedule: "0,5,10,15,20,25,30,35,40,45,50,55 7-18 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["gws_trumba"]
    - name: sync-accounts-from-gws-to-trumba-evening
      schedule: "0,10,20,30,40,50 19-22 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["gws_trumba"]
    - name: sync-accounts-from-gws-to-trumba-weekend
      schedule: "0 22 * * 6,7"
      command: ["/scripts/management_command.sh"]
      args: ["gws_trumba"]

    - name: sync-cal-from-trumba-to-gws-day
      schedule: "2,7,15,17,22,27,32,37,42,47,52,57 7-18 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["trumba_gws"]
    - name: sync-cal-from-trumba-to-gws-evening
      schedule: "5,15,25,35,45,55 19-22 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["trumba_gws"]
    - name: sync-cal-from-trumba-to-gws-weekend
      schedule: "30 22 * * 6,7"
      command: ["/scripts/management_command.sh"]
      args: ["trumba_gws"]

    - name: purge-inactive-accuonts
      schedule: "0 2 1 * *"
      command: ["/scripts/management_command.sh"]
      args: ["purge_accounts"]

environmentVariables:
  - name: ENV
    value: prod

  - name: GWS_ENV
    value: PROD
  - name: GWS_TIMEOUT
    value: "120"

  - name: TRUMBA_SEA_ENV
    value: PROD
  - name: TRUMBA_SEA_TIMEOUT
    value: "30"

  - name: TRUMBA_BOT_ENV
    value: PROD
  - name: TRUMBA_BOT_TIMEOUT
    value: "30"

  - name: TRUMBA_TAC_ENV
    value: PROD
  - name: TRUMBA_TAC_TIMEOUT
    value: "30"

externalSecrets:
  enabled: true
  secrets:
    - name: eventcal.uw.edu-secrets
      externalKey: axdd/kv/data/eventcal/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: email-host
          property: email-host
        - name: git-crypt-key
          property: git-crypt-key
    - name: eventcal.uw.edu-trumba-secrets
      externalKey: axdd/kv/data/eventcal/shared/trumba-secrets
      data:
        - name: trumba-sea-id
          property: trumba-sea-id
        - name: trumba-sea-pswd
          property: trumba-sea-pswd
        - name: trumba-bot-id
          property: trumba-bot-id
        - name: trumba-bot-pswd
          property: trumba-bot-pswd
        - name: trumba-tac-id
          property: trumba-tac-id
        - name: trumba-tac-pswd
          property: trumba-tac-pswd
    - name: eventcal.uw.edu-sql-secrets
      externalKey: axdd/kv/data/eventcal/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: eventcal.uw.edu-uwca-certs
      externalKey: axdd/kv/data/eventcal/shared/uwca-certs
      data:
        - name: eventcal.uw.edu-uwca.cert
          property: eventcal.uw.edu-uwca.cert
        - name: eventcal.uw.edu-uwca.key
          property: eventcal.uw.edu-uwca.key

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: eventcal.uw.edu-secrets
    secretKey: django-secret
  emailHost:
    name: EMAIL_HOST
    secretName: eventcal.uw.edu-secrets
    secretKey: email-host
  gitCryptKey:
    name: GIT_CRYPT_KEY
    secretName: eventcal.uw.edu-secrets
    secretKey: git-crypt-key
  trumbaSeaId:
    name: TRUMBA_SEA_ID
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-sea-id
  trumbaSeaPswd:
    name: TRUMBA_SEA_PSWD
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-sea-pswd
  trumbaBotId:
    name: TRUMBA_BOT_ID
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-bot-id
  trumbaBotPswd:
    name: TRUMBA_BOT_PSWD
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-bot-pswd
  trumbaTacId:
    name: TRUMBA_TAC_ID
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-tac-id
  trumbaTacPswd:
    name: TRUMBA_TAC_PSWD
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-tac-pswd
