ingress:
  enabled: false
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
  podsSpanNodes: true
readiness:
  enabled: true
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
repo: eventcal
instance: prod

externalService:
  enabled: true
  name: eventcal-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.41
  servicePort: 5432
database:
  engine: postgres
  name: eventcal
  hostname: eventcal-db-service
  secretName: eventcal.uw.edu-sql-secrets

certs:
  mounted: true
  certPath: /certs/eventcal.washington.edu-ic.cert
  keyPath: /certs/eventcal.washington.edu-ic.key
  secretName: eventcal.uw.edu-ic-certs
mountedSecrets:
  enabled: true
  mountPath: /csv
  secretName: eventcal.uw.edu-data-files

cronjob:
  enabled: true
  jobs:
    - name: gws-trumba-daytime
      schedule: "0,12,24,36,48 14-23 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["gws_trumba"]
      resources:
        limits:
          cpu: 200m
          memory: 384Mi
        requests:
          cpu: 100m
          memory: 128Mi
    - name: gws-trumba-evening
      schedule: "0,12,24,36,48 0-2 * * 2-6"
      command: ["/scripts/management_command.sh"]
      args: ["gws_trumba"]
      resources:
        limits:
          cpu: 200m
          memory: 384Mi
        requests:
          cpu: 100m
          memory: 128Mi
    - name: gws-trumba-weekend
      schedule: "0 5 * * 0,1"
      command: ["/scripts/management_command.sh"]
      args: ["gws_trumba"]
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi

    - name: trumba-gws-lite-day
      schedule: "5,10,15,20,25,30,35,40,45,50,55 14-23 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["trumba_gcal_gws"]
      resources:
        limits:
          cpu: 75m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 96Mi
    - name: trumba-gws-lite-evening
      schedule: "5,15,25,35,45,55 0-2 * * 2-6"
      command: ["/scripts/management_command.sh"]
      args: ["trumba_gcal_gws"]
      resources:
        limits:
          cpu: 75m
          memory: 196Mi
        requests:
          cpu: 25m
          memory: 96Mi
    - name: trumba-gws-2
      schedule: "30 5,13 * * 0-6"
      command: ["/scripts/management_command.sh"]
      args: ["trumba_gws"]
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 96Mi

    - name: purge-inactive-accs
      schedule: "0 10 3 * *"
      command: ["/scripts/management_command.sh"]
      args: ["purge_accounts"]
      resources:
        limits:
          cpu: 25m
          memory: 196Mi
        requests:
          cpu: 10m
          memory: 128Mi

environmentVariables:
  - name: ENV
    value: prod

  - name: CLUSTER_CNAME
    value: eventcal.uw.edu

  - name: SESSION_BACKEND
    value: MEMCACHED

  - name: GWS_ENV
    value: PROD
  - name: GWS_TIMEOUT
    value: "120"

  - name: TRUMBA_SEA_ENV
    value: PROD
  - name: TRUMBA_SEA_TIMEOUT
    value: "30"

  - name: TRUMBA_BOT_ENV
    value: PROD
  - name: TRUMBA_BOT_TIMEOUT
    value: "30"

  - name: TRUMBA_TAC_ENV
    value: PROD
  - name: TRUMBA_TAC_TIMEOUT
    value: "30"

externalSecrets:
  enabled: true
  secrets:
    - name: eventcal.uw.edu-secrets
      externalKey: eventcal/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: email-host
          property: email-host
    - name: eventcal.uw.edu-sql-secrets
      externalKey: eventcal/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: userpass
    - name: eventcal.uw.edu-trumba-secrets
      externalKey: eventcal/shared/trumba-secrets
      data:
        - name: trumba-sea-id
          property: trumba-sea-id
        - name: trumba-sea-pswd
          property: trumba-sea-pswd
        - name: trumba-bot-id
          property: trumba-bot-id
        - name: trumba-bot-pswd
          property: trumba-bot-pswd
        - name: trumba-tac-id
          property: trumba-tac-id
        - name: trumba-tac-pswd
          property: trumba-tac-pswd
    - name: eventcal.uw.edu-ic-certs
      externalKey: eventcal/shared/ic-certs
      data:
        - name: eventcal.washington.edu-ic.cert
          property: eventcal.washington.edu-ic.cert
        - name: eventcal.washington.edu-ic.key
          property: eventcal.washington.edu-ic.key
    - name: eventcal.uw.edu-data-files
      externalKey: eventcal/shared/data-files
      data:
        - name: accounts.csv
          property: accounts.csv

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: eventcal.uw.edu-secrets
    secretKey: django-secret
  emailHost:
    name: EMAIL_HOST
    secretName: eventcal.uw.edu-secrets
    secretKey: email-host
  trumbaSeaId:
    name: TRUMBA_SEA_ID
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-sea-id
  trumbaSeaPswd:
    name: TRUMBA_SEA_PSWD
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-sea-pswd
  trumbaBotId:
    name: TRUMBA_BOT_ID
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-bot-id
  trumbaBotPswd:
    name: TRUMBA_BOT_PSWD
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-bot-pswd
  trumbaTacId:
    name: TRUMBA_TAC_ID
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-tac-id
  trumbaTacPswd:
    name: TRUMBA_TAC_PSWD
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-tac-pswd
