ingress:
  enabled: false
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
  podsSpanNodes: true
readiness:
  enabled: true
database:
  engine: null
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
repo: eventcal
instance: prod
image:
  repository: gcr.io/uwit-mci-axdd/eventcal
  tag: IMAGE_TAG
certs:
  mounted: true
  certPath: /certs/eventcal.uw.edu-uwca.cert
  keyPath: /certs/eventcal.uw.edu-uwca.key
  secretName: eventcal.uw.edu-uwca-certs
mountedSecrets:
  enabled: true
  mountPath: /csv
  secretName: eventcal.uw.edu-data-files

cronjob:
  enabled: true
  jobs:
    - name: gws-trumba-daytime
      schedule: "6,18,30,42,54 14-23 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["gws_trumba"]
    - name: gws-trumba-evening
      schedule: "6,18,30,42,54 0-2 * * 2-6"
      command: ["/scripts/management_command.sh"]
      args: ["gws_trumba"]
    - name: gws-trumba-weekend
      schedule: "0 5 * * 0,1"
      command: ["/scripts/management_command.sh"]
      args: ["gws_trumba"]

    - name: trumba-gws-daytime
      schedule: "0,12,24,36,48 14-23 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["trumba_gws"]
    - name: trumba-gws-evening
      schedule: "0,12,24,36,48 0-2 * * 2-6"
      command: ["/scripts/management_command.sh"]
      args: ["trumba_gws"]
    - name: trumba-gws-weekend
      schedule: "30 5 * * 0,1"
      command: ["/scripts/management_command.sh"]
      args: ["trumba_gws"]

    - name: purge-inactive-accs
      schedule: "0 10 1 * *"
      command: ["/scripts/management_command.sh"]
      args: ["purge_accounts"]

environmentVariables:
  - name: ENV
    value: prod

  - name: CLUSTER_CNAME
    value: eventcal.uw.edu

  - name: SESSION_BACKEND
    value: MEMCACHED

  - name: GWS_ENV
    value: PROD
  - name: GWS_TIMEOUT
    value: "120"

  - name: TRUMBA_SEA_ENV
    value: PROD
  - name: TRUMBA_SEA_TIMEOUT
    value: "30"

  - name: TRUMBA_BOT_ENV
    value: PROD
  - name: TRUMBA_BOT_TIMEOUT
    value: "30"

  - name: TRUMBA_TAC_ENV
    value: PROD
  - name: TRUMBA_TAC_TIMEOUT
    value: "30"

externalSecrets:
  enabled: true
  secrets:
    - name: eventcal.uw.edu-secrets
      externalKey: axdd/kv/data/eventcal/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: email-host
          property: email-host
    - name: eventcal.uw.edu-trumba-secrets
      externalKey: axdd/kv/data/eventcal/shared/trumba-secrets
      data:
        - name: trumba-sea-id
          property: trumba-sea-id
        - name: trumba-sea-pswd
          property: trumba-sea-pswd
        - name: trumba-bot-id
          property: trumba-bot-id
        - name: trumba-bot-pswd
          property: trumba-bot-pswd
        - name: trumba-tac-id
          property: trumba-tac-id
        - name: trumba-tac-pswd
          property: trumba-tac-pswd
    - name: eventcal.uw.edu-uwca-certs
      externalKey: axdd/kv/data/eventcal/shared/uwca-certs
      data:
        - name: eventcal.uw.edu-uwca.cert
          property: eventcal.uw.edu-uwca.cert
        - name: eventcal.uw.edu-uwca.key
          property: eventcal.uw.edu-uwca.key
    - name: eventcal.uw.edu-data-files
      externalKey: axdd/kv/data/eventcal/shared/data-files
      data:
        - name: accounts.csv
          property: accounts.csv

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: eventcal.uw.edu-secrets
    secretKey: django-secret
  emailHost:
    name: EMAIL_HOST
    secretName: eventcal.uw.edu-secrets
    secretKey: email-host
  trumbaSeaId:
    name: TRUMBA_SEA_ID
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-sea-id
  trumbaSeaPswd:
    name: TRUMBA_SEA_PSWD
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-sea-pswd
  trumbaBotId:
    name: TRUMBA_BOT_ID
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-bot-id
  trumbaBotPswd:
    name: TRUMBA_BOT_PSWD
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-bot-pswd
  trumbaTacId:
    name: TRUMBA_TAC_ID
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-tac-id
  trumbaTacPswd:
    name: TRUMBA_TAC_PSWD
    secretName: eventcal.uw.edu-trumba-secrets
    secretKey: trumba-tac-pswd
