ingress:
  enabled: false
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
  podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true

memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate

repo: eventcal
instance: test

externalService:
  enabled: true
  name: eventcal-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.41
  servicePort: 5432

database:
  engine: postgres
  name: eventcal
  hostname: eventcal-db-service
  secretName: eventcal.uw.edu-sql-secrets

certs:
  mounted: true
  certPath: /certs/eventcal.washington.edu-ic.cert
  keyPath: /certs/eventcal.washington.edu-ic.key
  secretName: test.eventcal.uw.edu-ic-certs

mountedSecrets:
  enabled: true
  mountPath: /csv
  secretName: test.eventcal.uw.edu-data-files

cronjob:
  enabled: false

environmentVariables:
  - name: ENV
    value: test

  - name: CLUSTER_CNAME
    value: test.eventcal.uw.edu

  - name: SESSION_BACKEND
    value: MEMCACHED

  - name: GWS_ENV
    value: PROD
  - name: GWS_TIMEOUT
    value: "30"

  - name: TRUMBA_SEA_ENV
    value: PROD
  - name: TRUMBA_SEA_TIMEOUT
    value: "30"

  - name: TRUMBA_BOT_ENV
    value: PROD
  - name: TRUMBA_BOT_TIMEOUT
    value: "30"

  - name: TRUMBA_TAC_ENV
    value: PROD
  - name: TRUMBA_TAC_TIMEOUT
    value: "30"

externalSecrets:
  enabled: true
  secrets:
    - name: test.eventcal.uw.edu-secrets
      externalKey: eventcal/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: email-host
          property: email-host
        - name: safe-email-recipient
          property: safe-email-recipient
    - name: eventcal.uw.edu-sql-secrets
      externalKey: eventcal/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: userpass
    - name: test.eventcal.uw.edu-trumba-secrets
      externalKey: eventcal/shared/trumba-secrets
      data:
        - name: trumba-sea-id
          property: trumba-sea-id
        - name: trumba-sea-pswd
          property: trumba-sea-pswd
        - name: trumba-bot-id
          property: trumba-bot-id
        - name: trumba-bot-pswd
          property: trumba-bot-pswd
        - name: trumba-tac-id
          property: trumba-tac-id
        - name: trumba-tac-pswd
          property: trumba-tac-pswd
    - name: test.eventcal.uw.edu-ic-certs
      externalKey: eventcal/shared/ic-certs
      data:
        - name: eventcal.washington.edu-ic.cert
          property: eventcal.washington.edu-ic.cert
        - name: eventcal.washington.edu-ic.key
          property: eventcal.washington.edu-ic.key
    - name: test.eventcal.uw.edu-data-files
      externalKey: eventcal/shared/data-files
      data:
        - name: accounts.csv
          property: accounts.csv

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.eventcal.uw.edu-secrets
    secretKey: django-secret
  emailHost:
    name: EMAIL_HOST
    secretName: test.eventcal.uw.edu-secrets
    secretKey: email-host
  safeEmailRecipient:
    name: SAFE_EMAIL_RECIPIENT
    secretName: test.eventcal.uw.edu-secrets
    secretKey: safe-email-recipient
  trumbaSeaId:
    name: TRUMBA_SEA_ID
    secretName: test.eventcal.uw.edu-trumba-secrets
    secretKey: trumba-sea-id
  trumbaSeaPswd:
    name: TRUMBA_SEA_PSWD
    secretName: test.eventcal.uw.edu-trumba-secrets
    secretKey: trumba-sea-pswd
  trumbaBotId:
    name: TRUMBA_BOT_ID
    secretName: test.eventcal.uw.edu-trumba-secrets
    secretKey: trumba-bot-id
  trumbaBotPswd:
    name: TRUMBA_BOT_PSWD
    secretName: test.eventcal.uw.edu-trumba-secrets
    secretKey: trumba-bot-pswd
  trumbaTacId:
    name: TRUMBA_TAC_ID
    secretName: test.eventcal.uw.edu-trumba-secrets
    secretKey: trumba-tac-id
  trumbaTacPswd:
    name: TRUMBA_TAC_PSWD
    secretName: test.eventcal.uw.edu-trumba-secrets
    secretKey: trumba-tac-pswd
