repo: eventcal
instance: test
image:
  repository: registry.hub.docker.com/acait/eventcal
  tag: IMAGE_TAG
certs:
  mounted: true
  certPath: /certs/test.eventcal.uw.edu-uwca.cert
  keyPath: /certs/test.eventcal.uw.edu-uwca.key
  secretName: test.eventcal.uw.edu-uwca-certs

cronjob:
  enabled: false

environmentVariables:
  - name: ENV
    value: test

  - name: GWS_ENV
    value: PROD
  - name: GWS_TIMEOUT
    value: "30"

  - name: TRUMBA_SEA_ENV
    value: PROD
  - name: TRUMBA_SEA_TIMEOUT
    value: "30"

  - name: TRUMBA_BOT_ENV
    value: PROD
  - name: TRUMBA_BOT_TIMEOUT
    value: "30"

  - name: TRUMBA_TAC_ENV
    value: PROD
  - name: TRUMBA_TAC_TIMEOUT
    value: "30"

externalSecrets:
  enabled: true
  secrets:
    - name: test.eventcal.uw.edu-secrets
      externalKey: axdd/kv/data/eventcal/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: email-host
          property: email-host
        - name: safe-email-recipient
          property: safe-email-recipient
    - name: test.eventcal.uw.edu-trumba-secrets
      externalKey: axdd/kv/data/eventcal/prod/trumba-secrets
      data:
        - name: trumba_sea_id
          property: trumba_sea_id
        - name: trumba_sea_pswd
          property: trumba_sea_pswd
        - name: trumba_bot_id
          property: trumba_bot_id
        - name: trumba_bot_pswd
          property: trumba_bot_pswd
        - name: trumba_tac_id
          property: trumba_tac_id
        - name: trumba_tac_pswd
          property: trumba_tac_pswd
    - name: test.eventcal.uw.edu-uwca-certs
      externalKey: axdd/kv/data/eventcal/prod/uwca-certs
      data:
        - name: eventcal.uw.edu-uwca.cert
          property: eventcal.uw.edu-uwca.cert
        - name: eventcal.uw.edu-uwca.key
          property: eventcal.uw.edu-uwca.key

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.eventcal.uw.edu-secrets
    secretKey: django-secret
  emailHost:
    name: EMAIL_HOST
    secretName: test.eventcal.uw.edu-secrets
    secretKey: email-host
  safeEmailRecipient:
    name: SAFE_EMAIL_RECIPIENT
    secretName: test.eventcal.uw.edu-secrets
    secretKey: safe-email-recipient
  trumbaSeaId:
    name: TRUMBA_SEA_ID
    secretName: test.eventcal.uw.edu-trumba-secrets
    secretKey: trumba_sea_id
  trumbaSeaPswd:
    name: TRUMBA_SEA_PSWD
    secretName: test.eventcal.uw.edu-trumba-secrets
    secretKey: trumba_sea_pswd
  trumbaBotId:
    name: TRUMBA_BOT_ID
    secretName: test.eventcal.uw.edu-trumba-secrets
    secretKey: trumba_bot_id
  trumbaBotPswd:
    name: TRUMBA_BOT_PSWD
    secretName: test.eventcal.uw.edu-trumba-secrets
    secretKey: trumba_bot_pswd
  trumbaTacId:
    name: TRUMBA_TAC_ID
    secretName: test.eventcal.uw.edu-trumba-secrets
    secretKey: trumba_tac_id
  trumbaTacPswd:
    name: TRUMBA_TAC_PSWD
    secretName: test.eventcal.uw.edu-trumba-secrets
    secretKey: trumba_tac_pswd
