repo: eventcal
instance: test
image:
  repository: registry.hub.docker.com/acait/eventcal
  tag: IMAGE_TAG
cronjob:
  enabled: true
certs:
  mounted: true
  certPath: /certs/test.eventcal.uw.edu-uwca.cert
  keyPath: /certs/test.eventcal.uw.edu-uwca.key
  secretName: test.eventcal.uw.edu-uwca-certs

environmentVariables:
  - name: ENV
    value: test
  - name: GWS_ENV
    value: PROD
  - name: TRUMBA_ENV
    value: PROD

externalSecrets:
  enabled: true
  secrets:
    - name: test.eventcal.uw.edu-secrets
      externalKey: axdd/kv/data/eventcal/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: email-host
          property: email-host
        - name: safe-email-recipient
          property: safe-email-recipient
    - name: test.eventcal.uw.edu-uwca-certs
      externalKey: axdd/kv/data/eventcal/test/uwca-certs
      data:
        - name: test.eventcal.uw.edu-uwca.cert
          property: test.eventcal.uw.edu-uwca.cert
        - name: test.eventcal.uw.edu-uwca.key
          property: test.eventcal.uw.edu-uwca.key

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.eventcal.uw.edu-secrets
    secretKey: django-secret
  emailHost:
    name: EMAIL_HOST
    secretName: test.eventcal.uw.edu-secrets
    secretKey: email-host
  safeEmailRecipient:
    name: SAFE_EMAIL_RECIPIENT
    secretName: test.eventcal.uw.edu-secrets
    secretKey: safe-email-recipient
