ingress:
  enabled: true
  tls:
    eventcal:
      secretName: test.eventcal.uw.edu-ingress-cert
      hosts:
        - test.eventcal.uw.edu
  hosts:
    eventcal:
      host: test.eventcal.uw.edu
      paths:
        - "/":
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
externalService:
  enabled: true
  name: eventcal-db-service
  type: ClusterIP
  serviceAddress: TODO
  servicePort: 3306
database:
  engine: mysql
  name: eventcal_test
  hostname: eventcal-db-service
  secretName: test.eventcal.uw.edu-sql-secrets
repo: eventcal
instance: test
image:
  repository: registry.hub.docker.com/acait/eventcal
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
cronjob:
  enabled: true
certs:
  mounted: true
  certPath: /certs/test.eventcal.uw.edu-uwca.cert
  keyPath: /certs/test.eventcal.uw.edu-uwca.key
  secretName: test.eventcal.uw.edu-uwca-certs

environmentVariables:
  - name: ENV
    value: test
  - name: GWS_ENV
    value: PROD
  - name: TRUMBA_ENV
    value: PROD
  - name: ADMIN_GROUP
    value: "u_netid_eventcal_admins"

externalSecrets:
  enabled: true
  secrets:
    - name: test.eventcal.uw.edu-secrets
      externalKey: axdd/kv/data/eventcal/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: email-host
          property: email-host
        - name: email-sender
          property: email-sender
        - name: safe-email-recipient
          property: safe-email-recipient
    - name: test.eventcal.uw.edu-sql-secrets
      externalKey: axdd/kv/data/eventcal/test/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: test.eventcal.uw.edu-uwca-certs
      externalKey: axdd/kv/data/eventcal/test/uwca-certs
      data:
        - name: test.eventcal.uw.edu-uwca.cert
          property: test.eventcal.uw.edu-uwca.cert
        - name: test.eventcal.uw.edu-uwca.key
          property: test.eventcal.uw.edu-uwca.key

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.eventcal.uw.edu-secrets
    secretKey: django-secret
  emailHost:
    name: EMAIL_HOST
    secretName: test.eventcal.uw.edu-secrets
    secretKey: email-host
  emailNoreplyAddress:
    name: EMAIL_SENDER
    secretName: test.eventcal.uw.edu-secrets
    secretKey: email-sender
  safeEmailRecipient:
    name: SAFE_EMAIL_RECIPIENT
    secretName: test.eventcal.uw.edu-secrets
    secretKey: safe-email-recipient
